name: Run lint and test 

on: pull_request

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '20.0.0'
      - run: yarn install --network-timeout 1000000
      - run: yarn lint:check
      - run: yarn test 
